Document: opentracker
Title: Debian opentracker Manual
Author: <insert document author here>
Abstract: This manual describes what opentracker is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/opentracker/opentracker.sgml.gz

Format: postscript
Files: /usr/share/doc/opentracker/opentracker.ps.gz

Format: text
Files: /usr/share/doc/opentracker/opentracker.text.gz

Format: HTML
Index: /usr/share/doc/opentracker/html/index.html
Files: /usr/share/doc/opentracker/html/*.html
